# Form implementation generated from reading ui file '.\DniDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(398, 306)
        Dialog.setStyleSheet("QDialog{\n"
"background-color:whitesmoke;\n"
"border:solid 2px black;\n"
"border-radius:4px;\n"
"}")
        self.line_dni = QtWidgets.QLineEdit(parent=Dialog)
        self.line_dni.setGeometry(QtCore.QRect(20, 90, 131, 22))
        self.line_dni.setObjectName("line_dni")
        self.cmb_Genre = QtWidgets.QComboBox(parent=Dialog)
        self.cmb_Genre.setGeometry(QtCore.QRect(20, 50, 131, 22))
        self.cmb_Genre.setCurrentText("")
        self.cmb_Genre.setObjectName("cmb_Genre")
        self.btn_ok = QtWidgets.QPushButton(parent=Dialog)
        self.btn_ok.setGeometry(QtCore.QRect(230, 260, 75, 24))
        self.btn_ok.setStyleSheet("QPushButton\n"
"{\n"
"color:whitesmoke;\n"
"background-color:rgb(202, 202, 202);\n"
"border:solid 1px black;\n"
"border-radius:3px; \n"
"border-style:hidden;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(86, 229, 78);\n"
"}")
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtWidgets.QPushButton(parent=Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(310, 260, 75, 24))
        self.btn_cancel.setStyleSheet("QPushButton{\n"
"color:whitesmoke;\n"
"background-color:rgb(202, 202, 202);\n"
"border:solid 1px black;\n"
"border-radius:3px; \n"
"border-style:hidden;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:red;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.lbl_invisible = QtWidgets.QLabel(parent=Dialog)
        self.lbl_invisible.setGeometry(QtCore.QRect(20, 140, 351, 41))
        self.lbl_invisible.setStyleSheet("QLabel{\n"
"background-color:grey;\n"
"color:white;\n"
"}")
        self.lbl_invisible.setText("")
        self.lbl_invisible.setObjectName("lbl_invisible")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(130, 10, 151, 21))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.line_dni.setPlaceholderText(_translate("Dialog", "Ingrese DNI:"))
        self.cmb_Genre.setPlaceholderText(_translate("Dialog", "Seleccionar Género:"))
        self.btn_ok.setText(_translate("Dialog", "OK"))
        self.btn_cancel.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "Ingrese los datos solicitados"))
